---
config:
  theme: mc
  look: classic
---
flowchart LR
    n3["nominal temperature"] --> n8(("\-"))
    n4["thermostat node"] -- on/off --> n5["heater"]
    n8 --> n4
    n7["actual temperature"] --> n8
    n5 --> n7
    n3@{ shape: lean-r}
    n4@{ shape: rect}
    n5@{ shape: rect}
    n7@{ shape: lean-r}